-- MySQL Script generated by MySQL Workbench
-- Fri May 18 16:27:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemacademias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemacademias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemacademias` DEFAULT CHARACTER SET utf8 ;
USE `sistemacademias` ;

-- -----------------------------------------------------
-- Table `sistemacademias`.`Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Academico` (
  `idAcademico` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `CalleDireccion` VARCHAR(25) NOT NULL,
  `ColDireccion` VARCHAR(25) NOT NULL,
  `NumDireccion` VARCHAR(4) NOT NULL,
  `CorreoFacultativo` VARCHAR(40) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Administrador` ENUM('cierto', 'falso') NOT NULL,
  `Apellidos` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idAcademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Academia` (
  `idAcademia` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `ProgramaEducativa` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcademia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`ExperienciaEducativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`ExperienciaEducativa` (
  `idExperiencia Educativa` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Creditos` INT(2) NOT NULL,
  `Academia_idAcademia` INT NOT NULL,
  PRIMARY KEY (`idExperiencia Educativa`),
  INDEX `fk_Experiencia Educativa_Academia1_idx` (`Academia_idAcademia` ASC),
  CONSTRAINT `fk_Experiencia Educativa_Academia1`
    FOREIGN KEY (`Academia_idAcademia`)
    REFERENCES `sistemacademias`.`Academia` (`idAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Curso` (
  `nrc` INT NOT NULL,
  `Seccion` ENUM('tarde', 'mañana') NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `Academico_idAcademico` VARCHAR(10) NOT NULL,
  `ExperienciaEducativa_idExperiencia Educativa` INT NOT NULL,
  `Bloque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nrc`),
  INDEX `fk_Curso_Academico1_idx` (`Academico_idAcademico` ASC),
  INDEX `fk_Curso_ExperienciaEducativa1_idx` (`ExperienciaEducativa_idExperiencia Educativa` ASC),
  CONSTRAINT `fk_Curso_Academico1`
    FOREIGN KEY (`Academico_idAcademico`)
    REFERENCES `sistemacademias`.`Academico` (`idAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_ExperienciaEducativa1`
    FOREIGN KEY (`ExperienciaEducativa_idExperiencia Educativa`)
    REFERENCES `sistemacademias`.`ExperienciaEducativa` (`idExperiencia Educativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`PlanDeAcademia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`PlanDeAcademia` (
  `idPlandeAcademia` INT NOT NULL,
  `Acuerdos` TEXT NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  `FechaAprobacion` DATE NOT NULL,
  `Academia_idAcademia` INT NOT NULL,
  PRIMARY KEY (`idPlandeAcademia`),
  INDEX `fk_Plan de Academia_Academia1_idx` (`Academia_idAcademia` ASC),
  CONSTRAINT `fk_Plan de Academia_Academia1`
    FOREIGN KEY (`Academia_idAcademia`)
    REFERENCES `sistemacademias`.`Academia` (`idAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`PlanDeCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`PlanDeCurso` (
  `idPlanDeCurso` INT NOT NULL,
  `Curso_nrc` INT NOT NULL,
  `ObjetivoGeneral` TEXT NOT NULL,
  PRIMARY KEY (`idPlanDeCurso`),
  INDEX `fk_Plan de curso_Curso1_idx` (`Curso_nrc` ASC),
  CONSTRAINT `fk_Plan de curso_Curso1`
    FOREIGN KEY (`Curso_nrc`)
    REFERENCES `sistemacademias`.`Curso` (`nrc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`AvanceProgramatico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`AvanceProgramatico` (
  `idAvanceProgramatico` INT NOT NULL,
  `FechaCreacion` DATE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Curso_nrc` INT NOT NULL,
  PRIMARY KEY (`idAvanceProgramatico`),
  INDEX `fk_AvanceProgramatico_Curso1_idx` (`Curso_nrc` ASC),
  CONSTRAINT `fk_AvanceProgramatico_Curso1`
    FOREIGN KEY (`Curso_nrc`)
    REFERENCES `sistemacademias`.`Curso` (`nrc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Minuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Minuta` (
  `idMinuta` INT NOT NULL,
  `Proyecto` VARCHAR(45) NULL,
  `Asunto` VARCHAR(45) NULL,
  `Organizador` VARCHAR(45) NULL,
  `Lugar` VARCHAR(45) NULL,
  `FechaReunion` DATE NULL,
  `Academia_idAcademia` INT NOT NULL,
  PRIMARY KEY (`idMinuta`),
  INDEX `fk_Minuta_Academia1_idx` (`Academia_idAcademia` ASC),
  CONSTRAINT `fk_Minuta_Academia1`
    FOREIGN KEY (`Academia_idAcademia`)
    REFERENCES `sistemacademias`.`Academia` (`idAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Actividades` (
  `Temas` TEXT NULL,
  `Inicio` VARCHAR(5) NULL,
  `Fin` VARCHAR(5) NULL,
  `LiderDiscusion` VARCHAR(45) NULL,
  `NumeroActividad` INT(2) NULL,
  `Minuta_idMinuta` INT NOT NULL,
  CONSTRAINT `fk_Actividades_Minuta1`
    FOREIGN KEY (`Minuta_idMinuta`)
    REFERENCES `sistemacademias`.`Minuta` (`idMinuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Acuerdos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Acuerdos` (
  `NumeroAcuerdo` INT(2) NULL,
  `Descripcion` TEXT NULL,
  `NombreEncargado` VARCHAR(45) NULL,
  `ApellidoEncargado` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Minuta_idMinuta` INT NOT NULL,
  INDEX `fk_Acuerdos_Minuta1_idx` (`Minuta_idMinuta` ASC),
  CONSTRAINT `fk_Acuerdos_Minuta1`
    FOREIGN KEY (`Minuta_idMinuta`)
    REFERENCES `sistemacademias`.`Minuta` (`idMinuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Asistentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Asistentes` (
  `Academico_idAcademico` VARCHAR(10) NOT NULL,
  `Minuta_idMinuta` INT NOT NULL,
  `Asistencia` ENUM('1', '0') NOT NULL,
  `Firma` ENUM('1', '0') NOT NULL,
  `FechaFirma` DATE NOT NULL,
  PRIMARY KEY (`Academico_idAcademico`, `Minuta_idMinuta`),
  INDEX `fk_Academico_has_Minuta_Minuta1_idx` (`Minuta_idMinuta` ASC),
  INDEX `fk_Academico_has_Minuta_Academico1_idx` (`Academico_idAcademico` ASC),
  CONSTRAINT `fk_Academico_has_Minuta_Academico1`
    FOREIGN KEY (`Academico_idAcademico`)
    REFERENCES `sistemacademias`.`Academico` (`idAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academico_has_Minuta_Minuta1`
    FOREIGN KEY (`Minuta_idMinuta`)
    REFERENCES `sistemacademias`.`Minuta` (`idMinuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`AcademicoporAcademia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`AcademicoporAcademia` (
  `Academico_idAcademico` VARCHAR(10) NOT NULL,
  `Academia_idAcademia` INT NOT NULL,
  `Rol` ENUM('coordinador', 'docente') NULL,
  PRIMARY KEY (`Academico_idAcademico`, `Academia_idAcademia`),
  INDEX `fk_Academico_has_Academia_Academia1_idx` (`Academia_idAcademia` ASC),
  INDEX `fk_Academico_has_Academia_Academico1_idx` (`Academico_idAcademico` ASC),
  CONSTRAINT `fk_Academico_has_Academia_Academico1`
    FOREIGN KEY (`Academico_idAcademico`)
    REFERENCES `sistemacademias`.`Academico` (`idAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academico_has_Academia_Academia1`
    FOREIGN KEY (`Academia_idAcademia`)
    REFERENCES `sistemacademias`.`Academia` (`idAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Unidad` (
  `numeroUnidad` INT NOT NULL,
  `PlanDeCurso_idPlanDeCurso1` INT NOT NULL,
  PRIMARY KEY (`numeroUnidad`, `PlanDeCurso_idPlanDeCurso1`),
  INDEX `fk_Unidad_PlanDeCurso2_idx` (`PlanDeCurso_idPlanDeCurso1` ASC),
  CONSTRAINT `fk_Unidad_PlanDeCurso2`
    FOREIGN KEY (`PlanDeCurso_idPlanDeCurso1`)
    REFERENCES `sistemacademias`.`PlanDeCurso` (`idPlanDeCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Temas` (
  `Unidad` INT(2) NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `Temascol` VARCHAR(45) NULL,
  `Unidad_numeroUnidad` INT NOT NULL,
  PRIMARY KEY (`Unidad_numeroUnidad`),
  CONSTRAINT `fk_Temas_Unidad1`
    FOREIGN KEY (`Unidad_numeroUnidad`)
    REFERENCES `sistemacademias`.`Unidad` (`numeroUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Evaluacion` (
  `Elemento` TEXT NOT NULL,
  `Porcentaje` INT(3) NOT NULL,
  `PlanDeAcademia_idPlandeAcademia` INT NOT NULL,
  PRIMARY KEY (`Elemento`),
  INDEX `fk_Evaluacion_PlanDeAcademia1_idx` (`PlanDeAcademia_idPlandeAcademia` ASC),
  CONSTRAINT `fk_Evaluacion_PlanDeAcademia1`
    FOREIGN KEY (`PlanDeAcademia_idPlandeAcademia`)
    REFERENCES `sistemacademias`.`PlanDeAcademia` (`idPlandeAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Objetivo` (
  `numObjetivo` INT NOT NULL,
  `nombre` TEXT NOT NULL,
  `PlanDeAcademia_idPlandeAcademia` INT NOT NULL,
  PRIMARY KEY (`numObjetivo`),
  INDEX `fk_Objetivo_PlanDeAcademia1_idx` (`PlanDeAcademia_idPlandeAcademia` ASC),
  CONSTRAINT `fk_Objetivo_PlanDeAcademia1`
    FOREIGN KEY (`PlanDeAcademia_idPlandeAcademia`)
    REFERENCES `sistemacademias`.`PlanDeAcademia` (`idPlandeAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Meta` (
  `numeroMeta` INT NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Objetivo_numObjetivo` INT NOT NULL,
  INDEX `fk_Meta_Objetivo1_idx` (`Objetivo_numObjetivo` ASC),
  PRIMARY KEY (`numeroMeta`),
  CONSTRAINT `fk_Meta_Objetivo1`
    FOREIGN KEY (`Objetivo_numObjetivo`)
    REFERENCES `sistemacademias`.`Objetivo` (`numObjetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`PrimerParcial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`PrimerParcial` (
  `nombreTema` TEXT NOT NULL,
  `ExperienciaEducativa_idExperiencia Educativa` INT NOT NULL,
  `PlanDeAcademia_idPlandeAcademia` INT NOT NULL,
  INDEX `fk_PrimerParcial_ExperienciaEducativa1_idx` (`ExperienciaEducativa_idExperiencia Educativa` ASC),
  INDEX `fk_PrimerParcial_PlanDeAcademia1_idx` (`PlanDeAcademia_idPlandeAcademia` ASC),
  CONSTRAINT `fk_PrimerParcial_ExperienciaEducativa1`
    FOREIGN KEY (`ExperienciaEducativa_idExperiencia Educativa`)
    REFERENCES `sistemacademias`.`ExperienciaEducativa` (`idExperiencia Educativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrimerParcial_PlanDeAcademia1`
    FOREIGN KEY (`PlanDeAcademia_idPlandeAcademia`)
    REFERENCES `sistemacademias`.`PlanDeAcademia` (`idPlandeAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`SegundoParcial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`SegundoParcial` (
  `nombreTema` TEXT NOT NULL,
  `ExperienciaEducativa_idExperiencia Educativa` INT NOT NULL,
  `PlanDeAcademia_idPlandeAcademia` INT NOT NULL,
  INDEX `fk_SegundoParcial_ExperienciaEducativa1_idx` (`ExperienciaEducativa_idExperiencia Educativa` ASC),
  INDEX `fk_SegundoParcial_PlanDeAcademia1_idx` (`PlanDeAcademia_idPlandeAcademia` ASC),
  CONSTRAINT `fk_SegundoParcial_ExperienciaEducativa1`
    FOREIGN KEY (`ExperienciaEducativa_idExperiencia Educativa`)
    REFERENCES `sistemacademias`.`ExperienciaEducativa` (`idExperiencia Educativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SegundoParcial_PlanDeAcademia1`
    FOREIGN KEY (`PlanDeAcademia_idPlandeAcademia`)
    REFERENCES `sistemacademias`.`PlanDeAcademia` (`idPlandeAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Evaluacion` (
  `Elemento` TEXT NOT NULL,
  `Porcentaje` INT(3) NOT NULL,
  `PlanDeAcademia_idPlandeAcademia` INT NOT NULL,
  PRIMARY KEY (`Elemento`),
  INDEX `fk_Evaluacion_PlanDeAcademia1_idx` (`PlanDeAcademia_idPlandeAcademia` ASC),
  CONSTRAINT `fk_Evaluacion_PlanDeAcademia1`
    FOREIGN KEY (`PlanDeAcademia_idPlandeAcademia`)
    REFERENCES `sistemacademias`.`PlanDeAcademia` (`idPlandeAcademia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`Avance` (
  `Porcentaje` INT NOT NULL,
  `Observaciones` TEXT NULL,
  `Unidad_numeroUnidad` INT NOT NULL,
  `AvanceProgramatico_idAvanceProgramatico` INT NOT NULL,
  PRIMARY KEY (`Unidad_numeroUnidad`, `AvanceProgramatico_idAvanceProgramatico`),
  INDEX `fk_Avance_AvanceProgramatico1_idx` (`AvanceProgramatico_idAvanceProgramatico` ASC),
  CONSTRAINT `fk_Avance_Unidad1`
    FOREIGN KEY (`Unidad_numeroUnidad`)
    REFERENCES `sistemacademias`.`Unidad` (`numeroUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avance_AvanceProgramatico1`
    FOREIGN KEY (`AvanceProgramatico_idAvanceProgramatico`)
    REFERENCES `sistemacademias`.`AvanceProgramatico` (`idAvanceProgramatico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemacademias`.`ActividadAcademia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemacademias`.`ActividadAcademia` (
  `numeroActividad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `semana` INT NOT NULL,
  `formaOperar` TEXT NOT NULL,
  `Meta_numeroMeta` INT NOT NULL,
  PRIMARY KEY (`numeroActividad`),
  INDEX `fk_ActividadAcademia_Meta1_idx` (`Meta_numeroMeta` ASC),
  CONSTRAINT `fk_ActividadAcademia_Meta1`
    FOREIGN KEY (`Meta_numeroMeta`)
    REFERENCES `sistemacademias`.`Meta` (`numeroMeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
